### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Anisha7** [MackRoe/checklist#1]
- I can't run your program more than once. Users should be able to manipulate the same list multiple times. Your running is set to None after the first selection. Why is that? (Hint: What does the select() function return at different stages of your code? Does it ever return true?)
- Debug you mark_completed() function. You are using variables that are not defined! Come to office hours if you need help. :)

**Comment by MackRoe** [comment]
Thank you for your critique. Please contact me via slack.
